### ISSUE TITLE
Unhandled error on empty file(?)

### ISSUE THREAD

**Issue by Alloyed** [excessive/iqm-exm#1]
So for some reason or another, blender decided to export what I'm assuming from the filesize is an empty mesh, and iqm.lua doesn't know what to make of it.
the iqm file:
https://alloyed.me/shared/probably_empty.iqm
traceback:

```
Error: rocks/share/lua/5.1/iqm/init.lua:173: declaration specifier expected near ';' at line 2
stack traceback:
    [C]: in function 'cdef'
    rocks/share/lua/5.1/iqm/init.lua:173: in function 'load'
    render.lua:94: in function 'f'
    main.lua:56: in function 'load_assets'
    main.lua:68: in function 'newA'
    rocks/share/lua/5.1/gabe/love.lua:20: in function 'load'
    [string "boot.lua"]:437: in function <[string "boot.lua"]:433>
    [C]: in function 'xpcall'
```

I haven't read the spec, so it might be that blender spit out an entirely invalid file. The details for that, just in case
- blender 2.76b hash f337fea
- iqm exporter 2015.8.3

**Comment by karai17** [comment]
When exporting an IQM from Blender, you must do a few things:
1. Apply all modifiers
2. Select everything you want to export (Meshes, armatures, etc.)
3. Correctly check the export options (disable bones if no armature, export material not material+image, etc.)

The IQM exporter we have in our repos has a few bug fixes and quality of life improvements that the upstream does not, so make sure you use our exporter.
