### ISSUE TITLE
feature request : disable optimization calculation for exporting very high poly models. 

### ISSUE THREAD

**Issue by plankatron** [excessive/iqm-exm#6]
hi there, a friend of mine and i were trying to modify your script to do this but ran into some weird errors. 
[exm_export.py.txt](https://github.com/excessive/iqm-exm/files/2788655/exm_export.py.txt)
and a copy of the error : 
[error.txt](https://github.com/excessive/iqm-exm/files/2788660/error.txt)

**Comment by shakesoda** [comment]
yeah sometimes it takes a while to run that step on complex meshes. looking into it now

**Comment by shakesoda** [comment]
figured it out, will commit soon.

to patch it: add this below `def optimize(self)` and replace the call to `mesh.optimize()` with `mesh.populate()` when optimization is disabled.

```python

    def populate(self):
        for v in self.verts:
            if v:
                v.index = -1

        vertschedule = []
        for tri in self.tris:
            for v in tri:
                if v.index < 0:
                    v.index = len(vertschedule)
                    vertschedule.append(v)

        self.verts = vertschedule
```
